name: Check PR size

on:
  pull_request:

jobs:
  check_pr_size:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check PR size
        uses: maidsafe/pr_size_checker@v2
        with:
          max_lines_changed: 500
