name: Some pull request checks

on:
  pull_request:

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Run TypeScript compiler
        run: yarn tsc

      # - name: Run Vitest
      #   run: yarn vitest:once
