name: Pull request checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  sonar_analysis:
    runs-on: windows-latest
    timeout-minutes: 15

    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Windows SDK 10.0.22621.0
        uses: ChristopheLav/windows-sdk-install@v1
        with:
          version-sdk: 22621
          features: "OptionId.DesktopCPPx86,OptionId.DesktopCPPx64"

      - name: Install node-gyp
        run: npm install -g node-gyp

      - name: Install build wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v5

      - name: Run build wrapper
        run: build-wrapper-win-x86-64.exe --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmd /c "node-gyp configure build"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.cfamily.compile-commands=${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json
